/**
 * Author:  guillermogallegogonzalez
 * Created: 7 nov 2022
 */

CREATE TABLE PROVINCIA(
    PROVINCIA_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE_PROVINCIA VARCHAR(20) NOT NULL,
    CONSTRAINT ID_PROVINCIA_PK PRIMARY KEY(PROVINCIA_ID)
);
 

CREATE TABLE ALUMNOS(
    DNI VARCHAR(9) NOT NULL,
    NOM_ALUMNO VARCHAR(30) NOT NULL,
    FOTO VARCHAR(30),
    DIRECCION VARCHAR(50),
    LOCALIDAD VARCHAR(30),
    TELEFONO VARCHAR(15),
    PROVINCIA INTEGER NOT NULL,
    CONSTRAINT ID_ALUMNOS_PK PRIMARY KEY (DNI),
    CONSTRAINT PROV_ALUMNOS_FK FOREIGN KEY (PROVINCIA) REFERENCES PROVINCIA(PROVINCIA_ID)
);
 
CREATE TABLE CURSOS(
    ID_CURSO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    IMPORTE_CURSO DECIMAL(7,2) NOT NULL,
    NOM_CURSO VARCHAR(30) NOT NULL,
    CATEGORIA VARCHAR(30) NOT NULL,
    DURACION INTEGER,
    PROVEEDOR VARCHAR(50),
    CERTIFICACION VARCHAR(30),
    BECA BOOLEAN,
    TIPO_CURSO VARCHAR(30) NOT NULL CHECK (TIPO_CURSO IN('OFICIAL', 'ONLINE', 'VIDEO BAJO DEMANDA')),
    N_ASISTENTES INTEGER,
    FECHA_INI DATE,
    FECHA_FIN DATE,
    INSTRUCTOR VARCHAR(30),
    CONSTRAINT ID_CURSOS_PK PRIMARY KEY (ID_CURSO)
);

CREATE TABLE MATRICULA(
    ID_MAT INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CURSO INTEGER NOT NULL,
    ALUMNO VARCHAR(9) NOT NULL,
    IMPORTE DECIMAL(7,2),
    NECESITA_CERT BOOLEAN NOT NULL,
    NECESITA_DOC BOOLEAN NOT NULL,
    TIPO_MAT VARCHAR(30) NOT NULL CHECK (TIPO_MAT IN('ORDINARIA', 'REPETIDOR', 'FAMILIA NUMEROSA')),
    F_MAT DATE NOT NULL,
    CONSTRAINT ID_MATRICULA_PK PRIMARY KEY (ID_MAT),
    CONSTRAINT ALUM_MATRICULA_FK FOREIGN KEY (ALUMNO) REFERENCES ALUMNOS(DNI),
    CONSTRAINT CURSO_MATRICULA_FK FOREIGN KEY (CURSO) REFERENCES CURSOS(ID_CURSO)
);




